# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f40d622bcff24250c967f480e6e420becec5ec62b58024385942ed847377848b49f1820a2a68a0d46f1ee04ae2e2b63cd652f695302b40b2b4f4408cb891ee5

test:
  secret_key_base: cd8e006f8434426071af0cae15129b44a42e1773db6da509e8e572474db6351c0efd4e3f193cf32bab6b64e40b9290e5fadf356c8327b197d934087a44264a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
